import { useState, useEffect } from 'react'

interface Props {
  prompt: string
  promptLang: 'en' | 'vi' | 'fr'
  onSetPromptLang: (lang: 'en' | 'vi' | 'fr') => void
  isWeeklyDigest: boolean
  onToggleWeeklyDigest: (weekly: boolean) => void
}

type Provider = 'gemini' | 'openai'

export default function InAppAIGenerator({
  prompt,
  promptLang,
  onSetPromptLang,
  isWeeklyDigest,
  onToggleWeeklyDigest,
}: Props) {
  const [provider, setProvider] = useState<Provider>(() => {
    return (localStorage.getItem('flatland_ai_provider') as Provider) || 'gemini'
  })
  const [apiKey, setApiKey] = useState<string>(() => {
    return localStorage.getItem('flatland_ai_key') || ''
  })
  const [showKeyConfig, setShowKeyConfig] = useState<boolean>(() => !localStorage.getItem('flatland_ai_key'))
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [generatedStory, setGeneratedStory] = useState<string>('')
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    try {
      localStorage.setItem('flatland_ai_provider', provider)
    } catch {}
  }, [provider])

  const saveApiKey = (key: string) => {
    setApiKey(key)
    try {
      localStorage.setItem('flatland_ai_key', key.trim())
    } catch {}
  }

  const handleGenerate = async () => {
    const trimmedKey = apiKey.trim()
    if (!trimmedKey) {
      setShowKeyConfig(true)
      setError('Please provide your API key first.')
      return
    }

    setLoading(true)
    setError(null)

    const langInstruction =
      promptLang === 'vi'
        ? '\n\nIMPORTANT SYSTEM INSTRUCTION: Write your entire response in Vietnamese (Tiếng Việt).'
        : promptLang === 'fr'
        ? '\n\nIMPORTANT SYSTEM INSTRUCTION: Write your entire response in French (Français).'
        : '\n\nIMPORTANT SYSTEM INSTRUCTION: Write your entire response in English.'

    const finalPrompt = prompt + langInstruction

    try {
      if (provider === 'gemini') {
        const model = 'gemini-1.5-flash'
        const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${trimmedKey}`
        const res = await fetch(url, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{ parts: [{ text: finalPrompt }] }],
            generationConfig: {
              temperature: 0.75,
              maxOutputTokens: 2500,
            },
          }),
        })

        const data = await res.json()
        if (!res.ok || data.error) {
          throw new Error(data.error?.message || `Gemini API Error (${res.status})`)
        }
        const text = data.candidates?.[0]?.content?.parts?.[0]?.text
        if (!text) throw new Error('No narrative generated by Gemini.')
        setGeneratedStory(text)
      } else {
        // OpenAI
        const model = 'gpt-4o-mini'
        const url = 'https://api.openai.com/v1/chat/completions'
        const res = await fetch(url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${trimmedKey}`,
          },
          body: JSON.stringify({
            model,
            messages: [
              {
                role: 'system',
                content:
                  'You are a legendary historian and bard recording the epic chronicles of the 2D universe of Flatland.',
              },
              { role: 'user', content: finalPrompt },
            ],
            temperature: 0.75,
          }),
        })

        const data = await res.json()
        if (!res.ok || data.error) {
          throw new Error(data.error?.message || `OpenAI API Error (${res.status})`)
        }
        const text = data.choices?.[0]?.message?.content
        if (!text) throw new Error('No narrative returned by OpenAI.')
        setGeneratedStory(text)
      }
    } catch (err: any) {
      setError(err.message || 'Failed to generate story.')
    } finally {
      setLoading(false)
    }
  }

  const copyStory = async () => {
    try {
      await navigator.clipboard.writeText(generatedStory)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // fallback
    }
  }

  const downloadStory = () => {
    const blob = new Blob([generatedStory], { type: 'text/markdown;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `flatland_ai_story_${provider}_${Date.now()}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
      {/* Controls Header */}
      <div
        style={{
          background: '#161b22',
          border: '1px solid #30363d',
          borderRadius: 8,
          padding: '10px 14px',
          display: 'flex',
          flexDirection: 'column',
          gap: 8,
        }}
      >
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 8 }}>
          {/* Language Selector (BM-5) */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <span style={{ fontSize: 11, color: '#8b949e', fontWeight: 600 }}>🌐 Story Language:</span>
            {(['en', 'vi', 'fr'] as const).map((lang) => (
              <button
                key={lang}
                type="button"
                className="chip"
                onClick={() => onSetPromptLang(lang)}
                style={{
                  padding: '2px 8px',
                  fontSize: 11,
                  fontWeight: promptLang === lang ? 700 : 500,
                  background: promptLang === lang ? '#1f6feb' : '#21262d',
                  borderColor: promptLang === lang ? '#388bfd' : '#30363d',
                  color: promptLang === lang ? '#fff' : '#c9d1d9',
                  cursor: 'pointer',
                }}
              >
                {lang === 'en' ? 'English' : lang === 'vi' ? 'Tiếng Việt' : 'Français'}
              </button>
            ))}
          </div>

          {/* This Week in Flatland (BM-4) */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <button
              type="button"
              className="chip"
              onClick={() => onToggleWeeklyDigest(!isWeeklyDigest)}
              style={{
                background: isWeeklyDigest ? '#a371f7' : '#21262d',
                borderColor: isWeeklyDigest ? '#bc8cff' : '#30363d',
                color: isWeeklyDigest ? '#fff' : '#c9d1d9',
                cursor: 'pointer',
                fontWeight: isWeeklyDigest ? 700 : 500,
              }}
              title="Focus prompt on the last 7 simulated days as a weekly newsletter"
            >
              📰 {isWeeklyDigest ? 'Past 7 Days (Weekly Digest)' : 'Full World Chronicle'}
            </button>

            <button
              type="button"
              className="chip"
              onClick={() => setShowKeyConfig(!showKeyConfig)}
              style={{
                background: showKeyConfig ? '#30363d' : '#21262d',
                color: '#8b949e',
                cursor: 'pointer',
              }}
              title="Configure AI Provider & Key"
            >
              ⚙️ Key Settings
            </button>
          </div>
        </div>

        {/* API Key Configuration Drawer */}
        {showKeyConfig && (
          <div
            style={{
              background: '#0d1117',
              border: '1px solid #21262d',
              borderRadius: 6,
              padding: '10px 12px',
              display: 'flex',
              flexDirection: 'column',
              gap: 8,
              marginTop: 4,
            }}
          >
            <div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}>
              <span style={{ fontSize: 11, color: '#8b949e' }}>Provider:</span>
              <button
                type="button"
                className="chip"
                onClick={() => setProvider('gemini')}
                style={{
                  background: provider === 'gemini' ? '#238636' : '#21262d',
                  color: provider === 'gemini' ? '#fff' : '#c9d1d9',
                  borderColor: provider === 'gemini' ? '#2ea043' : '#30363d',
                  cursor: 'pointer',
                  fontWeight: provider === 'gemini' ? 700 : 400,
                }}
              >
                ✨ Google Gemini (1.5 Flash)
              </button>
              <button
                type="button"
                className="chip"
                onClick={() => setProvider('openai')}
                style={{
                  background: provider === 'openai' ? '#238636' : '#21262d',
                  color: provider === 'openai' ? '#fff' : '#c9d1d9',
                  borderColor: provider === 'openai' ? '#2ea043' : '#30363d',
                  cursor: 'pointer',
                  fontWeight: provider === 'openai' ? 700 : 400,
                }}
              >
                🤖 OpenAI (GPT-4o Mini)
              </button>
            </div>

            <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
              <input
                type="password"
                placeholder={provider === 'gemini' ? 'Enter Google Gemini API key (AIzaSy...)' : 'Enter OpenAI API key (sk-...)'}
                value={apiKey}
                onChange={(e) => saveApiKey(e.target.value)}
                style={{
                  flex: 1,
                  background: '#161b22',
                  border: '1px solid #30363d',
                  borderRadius: 6,
                  padding: '6px 10px',
                  color: '#e6edf3',
                  fontSize: 12,
                }}
              />
              {apiKey && (
                <button
                  type="button"
                  onClick={() => saveApiKey('')}
                  className="chip"
                  style={{ cursor: 'pointer', color: '#f85149' }}
                >
                  Clear
                </button>
              )}
            </div>

            <span style={{ fontSize: 10.5, color: '#6e7681' }}>
              🔒 <b>Client-side only:</b> Your key is stored exclusively in your browser's <code>localStorage</code> and calls the API directly. It is NEVER sent to our server.
            </span>
          </div>
        )}

        {/* Generate Button Row */}
        <div style={{ display: 'flex', gap: 8, alignItems: 'center', justifyContent: 'space-between', marginTop: 4 }}>
          <button
            type="button"
            onClick={handleGenerate}
            disabled={loading}
            style={{
              flex: 1,
              background: loading ? '#1f6feb66' : '#1f6feb',
              color: '#fff',
              border: 'none',
              borderRadius: 6,
              padding: '8px 16px',
              fontSize: 13,
              fontWeight: 700,
              cursor: loading ? 'wait' : 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 8,
            }}
          >
            {loading ? '⏳ Composing Chronicle Narrative...' : '✨ Generate Story with AI'}
          </button>
        </div>

        {error && (
          <div style={{ color: '#ff7b72', fontSize: 11.5, background: 'rgba(248,81,73,0.1)', padding: '6px 10px', borderRadius: 6, border: '1px solid #f85149' }}>
            ⚠️ {error}
          </div>
        )}
      </div>

      {/* Generated Story Display */}
      {generatedStory && (
        <div
          style={{
            background: '#161b22',
            border: '1px solid #30363d',
            borderRadius: 8,
            padding: '14px 18px',
            display: 'flex',
            flexDirection: 'column',
            gap: 10,
          }}
        >
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #21262d', paddingBottom: 8 }}>
            <span style={{ fontWeight: 700, color: '#e6edf3', fontSize: 13 }}>
              📖 AI Generated Narrative ({provider === 'gemini' ? 'Gemini 1.5 Flash' : 'GPT-4o Mini'})
            </span>
            <div style={{ display: 'flex', gap: 6 }}>
              <button
                type="button"
                className="chip"
                onClick={copyStory}
                style={{ cursor: 'pointer', background: copied ? '#238636' : '#21262d', color: copied ? '#fff' : '#c9d1d9' }}
              >
                {copied ? '✓ Copied!' : '📋 Copy Story'}
              </button>
              <button
                type="button"
                className="chip"
                onClick={downloadStory}
                style={{ cursor: 'pointer' }}
              >
                💾 Download .md
              </button>
            </div>
          </div>

          <div
            style={{
              maxHeight: 380,
              overflowY: 'auto',
              fontSize: 12.5,
              lineHeight: 1.65,
              color: '#c9d1d9',
              whiteSpace: 'pre-wrap',
              fontFamily: 'system-ui, -apple-system, sans-serif',
            }}
          >
            {generatedStory}
          </div>
        </div>
      )}
    </div>
  )
}
